### ISSUE TITLE
JavaScript / TypeScript

### ISSUE THREAD

**Issue by romansilivestrov** [coder1x/MetaLamp_four_task#11]
`async` и `await` используются для работы с промисами. В слайдере, где весь код синхронный они не к чему.

Тип `void` используется только для функций, [которые не возвращают значение](https://www.typescriptlang.org/docs/handbook/2/functions.html#void):
![image](https://user-images.githubusercontent.com/85496220/176117784-2ac4f5c2-bd45-47d4-8813-63422d1fa6cf.png)

**Comment by romansilivestrov** [comment]
Много где встечаются [type assertions](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#type-assertions), что нежелательно.

![image](https://user-images.githubusercontent.com/85496220/176880518-eadd4415-7075-4136-a899-71eb6ef50d67.png)
в подобных местах их можно избежать, добавив проверку или сделав операцию [опциональной](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

**Comment by romansilivestrov** [comment]
Насколько я понял, `this.rangeSliderName` - это константа, которая присваивается единожды. Соответственно, её лучше импортировать из файла констант, вместо того, чтобы передавать как параметр в компоненты.

**Comment by osyka-yuri** [comment]
Очень часто используется type assertion при поиске по dom дереву, неспроста же ведь там тип Element | null, так как элемент может быть как найден так и нет, и typescript соответственно подталкивает нас чтобы мы делали проверку на то что элемент был действительно найден это сделает код более надежным и менее подверженным ошибкам.
То же относится и к событиям, везде где используется event.target используется type assertion, чтобы действительно убиться что там находится нужный нам тип элемента можно использовать `event.target instanceof HTMLDivElement`.

---

https://github.com/coder1x/MetaLamp_four_task/blob/1faf42a254d3ae756b076595d218b40dbb3611fe/src/plugins/rangeSliderFox/mvc/model/Model.ts#L423
Здесь, по-моему, вообще бессмысленный type assertion
